"""Claude exporter: generates CLAUDE.md for Claude Code / Claude API."""

from __future__ import annotations

from loom_context.exporters.base import BaseExporter


class ClaudeExporter(BaseExporter):
    """Export context as CLAUDE.md for Claude Code."""

    agent_name = "claude"
    file_extension = ".md"

    def export(self) -> str:
        """Generate CLAUDE.md content."""
        prompt = self._read_prompt()

        lines: list[str] = []
        lines.append("# Project Context for Claude\n")
        lines.append("<!-- Generated by Loom-Context. Do not edit manually. -->\n")
        lines.append(prompt)

        return "\n".join(lines)

    def default_filename(self) -> str:
        return "CLAUDE.md"
