"""Codex exporter: generates AGENTS.md for OpenAI Codex / CLI agents."""

from __future__ import annotations

import json

from loom_context.exporters.base import BaseExporter


class CodexExporter(BaseExporter):
    """Export context as AGENTS.md for Codex-style agents."""

    agent_name = "codex"
    file_extension = ".md"

    def export(self) -> str:
        """Generate AGENTS.md content."""
        index_raw = self._read_file("index.json")
        index = json.loads(index_raw) if index_raw else {}

        project = index.get("project", {})
        quick_rules = index.get("quick_rules", [])

        lines: list[str] = []
        lines.append("# AGENTS.md")
        lines.append("<!-- Generated by Loom-Context. Do not edit manually. -->\n")

        # Project overview
        lines.append("## Project Overview\n")
        lines.append(f"- **Name:** {project.get('name', '?')}")
        lines.append(f"- **Type:** {project.get('type', '?')}")
        lines.append(f"- **Architecture:** {', '.join(project.get('architecture', []))}")
        lines.append(f"- **Language:** {project.get('language', '?')}")
        lines.append(f"- **Runtime:** {project.get('runtime', '?')}")
        lines.append("")

        # Rules as directives
        if quick_rules:
            lines.append("## Directives\n")
            lines.append("Follow these rules in all code changes:\n")
            for rule in quick_rules:
                lines.append(f"- {rule}")
            lines.append("")

        # Architecture
        architecture = self._read_file("architecture.md")
        if architecture:
            lines.append("## Architecture\n")
            lines.append(architecture)

        # Directory structure
        directory_map = self._read_file("directory-map.md")
        if directory_map:
            lines.append("## Directory Structure\n")
            lines.append(directory_map)

        return "\n".join(lines)

    def default_filename(self) -> str:
        return "AGENTS.md"
