"""Copilot exporter: generates .github/copilot-instructions.md for GitHub Copilot."""

from __future__ import annotations

import json
from pathlib import Path

from loom_context.exporters.base import BaseExporter


class CopilotExporter(BaseExporter):
    """Export context as copilot-instructions.md for GitHub Copilot."""

    agent_name = "copilot"
    file_extension = ".md"

    def export(self) -> str:
        """Generate copilot-instructions.md content."""
        index_raw = self._read_file("index.json")
        index = json.loads(index_raw) if index_raw else {}

        project = index.get("project", {})
        quick_rules = index.get("quick_rules", [])

        lines: list[str] = []
        lines.append("# Copilot Instructions")
        lines.append(f"<!-- Generated by Loom-Context for {project.get('name', 'project')} -->")
        lines.append("")

        # Project context
        lines.append("## Project")
        lines.append(f"- **Type:** {project.get('type', '?')}")
        lines.append(f"- **Architecture:** {', '.join(project.get('architecture', []))}")
        lines.append(f"- **Language:** {project.get('language', '?')}")
        lines.append(f"- **Runtime:** {project.get('runtime', '?')}")
        lines.append("")

        # Rules as instructions
        if quick_rules:
            lines.append("## Rules (MUST follow)")
            lines.append("")
            for rule in quick_rules:
                lines.append(f"- {rule}")
            lines.append("")

        # Architecture overview
        architecture = self._read_file("architecture.md")
        if architecture:
            lines.append("## Architecture")
            lines.append("")
            # Extract key sections, skip verbose headers
            for line in architecture.split("\n"):
                stripped = line.strip()
                if stripped and not stripped.startswith("# "):
                    lines.append(line)
            lines.append("")

        # Naming conventions
        naming = self._read_file("naming.md")
        if naming:
            lines.append("## Naming Conventions")
            lines.append("")
            for line in naming.split("\n"):
                stripped = line.strip()
                if stripped and not stripped.startswith("# "):
                    lines.append(line)
            lines.append("")

        # Directory map (compact)
        dir_map = self._read_file("directory-map.md")
        if dir_map:
            lines.append("## Directory Structure")
            lines.append("")
            for line in dir_map.split("\n"):
                stripped = line.strip()
                if stripped and not stripped.startswith("#") and not stripped.startswith("**"):
                    lines.append(line)
            lines.append("")

        # Plans summary (only active)
        plans = self._read_file("plans-summary.md")
        if plans:
            # Only include Active Plans section if it exists
            in_active = False
            for line in plans.split("\n"):
                if "## Active Plans" in line:
                    in_active = True
                    lines.append("## Active Plans")
                    lines.append("")
                    continue
                if in_active and line.startswith("## "):
                    break
                if in_active and line.strip():
                    lines.append(line)
            if in_active:
                lines.append("")

        # Footer
        lines.append("---")
        lines.append(
            "These instructions were generated by Loom-Context. "
            "All suggestions MUST comply with the rules above."
        )

        return "\n".join(lines)

    def default_filename(self) -> str:
        return "copilot-instructions.md"

    def install_path(self) -> Path:
        github_dir = self.root / ".github"
        github_dir.mkdir(exist_ok=True)
        return github_dir / "copilot-instructions.md"
