"""Cursor exporter: generates .cursorrules for Cursor IDE."""

from __future__ import annotations

import json

from loom_context.exporters.base import BaseExporter


class CursorExporter(BaseExporter):
    """Export context as .cursorrules for Cursor IDE."""

    agent_name = "cursor"
    file_extension = ""

    def export(self) -> str:
        """Generate .cursorrules content."""
        index_raw = self._read_file("index.json")
        index = json.loads(index_raw) if index_raw else {}

        project = index.get("project", {})
        quick_rules = index.get("quick_rules", [])

        lines: list[str] = []
        lines.append("# Cursor Rules")
        lines.append(f"# Generated by Loom-Context from {project.get('name', 'project')}\n")

        # Project info
        lines.append(f"Project: {project.get('name', '?')}")
        lines.append(f"Type: {project.get('type', '?')}")
        lines.append(f"Architecture: {', '.join(project.get('architecture', []))}")
        lines.append(f"Language: {project.get('language', '?')}")
        lines.append(f"Runtime: {project.get('runtime', '?')}")
        lines.append("")

        # Rules
        if quick_rules:
            lines.append("## Rules\n")
            for rule in quick_rules:
                lines.append(f"- {rule}")
            lines.append("")

        # Architecture
        architecture = self._read_file("architecture.md")
        if architecture:
            lines.append("## Architecture\n")
            lines.append(architecture)

        # Naming
        naming = self._read_file("naming.md")
        if naming:
            lines.append("## Naming Conventions\n")
            lines.append(naming)

        return "\n".join(lines)

    def default_filename(self) -> str:
        return ".cursorrules"
