"""Agent detection: discover which agent files exist in a project."""

from __future__ import annotations

from pathlib import Path
from typing import Optional

# Agent name → expected filename in project root
AGENT_FILES: dict[str, str] = {
    "claude": "CLAUDE.md",
    "cursor": ".cursorrules",
    "codex": "AGENTS.md",
    "copilot": ".github/copilot-instructions.md",
    "generic": ".loom-export.md",
}


def detect_installed_agents(root: Path) -> dict[str, Path]:
    """Return {agent_name: existing_file_path} for agents already installed."""
    found: dict[str, Path] = {}
    for agent, filename in AGENT_FILES.items():
        path = root / filename
        if path.exists():
            found[agent] = path
    return found


def detect_available_agents() -> list[str]:
    """Return all supported agent names."""
    return list(AGENT_FILES.keys())


def agent_file_info(path: Path) -> Optional[dict[str, str]]:
    """Return basic info about an existing agent file."""
    if not path.exists():
        return None
    size = path.stat().st_size
    size_str = f"{size} B" if size < 1024 else f"{size / 1024:.1f} KB"

    # Check if generated by Loom
    try:
        head = path.read_text(encoding="utf-8")[:200]
        is_loom = "Loom-Context" in head or "loom" in head.lower()
        origin = "generated by Loom" if is_loom else "hand-crafted"
    except OSError:
        origin = "unknown"

    return {"size": size_str, "origin": origin}
