"""Prompt generator: assembles all .context/ into a single AI system prompt."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Optional


class PromptGenerator:
    """Generates the master AI system prompt from .context/ files."""

    def __init__(self, context_dir: Path) -> None:
        self.context_dir = context_dir

    def generate(self) -> str:
        """Read .context/ and compose master prompt."""
        sections: list[str] = []

        # Header
        index = self._read_json("index.json")
        if index:
            project = index.get("project", {})
            sections.append(f"# Project Context: {project.get('name', 'Unknown')}")
            sections.append(f"**Type:** {project.get('type', 'unknown')}")
            sections.append(f"**Architecture:** {', '.join(project.get('architecture', []))}")
            sections.append(f"**Language:** {project.get('language', 'unknown')}")
            sections.append(f"**Runtime:** {project.get('runtime', 'unknown')}")
            sections.append("")

            # Quick rules (immediate context)
            quick_rules = index.get("quick_rules", [])
            if quick_rules:
                sections.append("## Quick Rules (MUST follow)")
                for rule in quick_rules:
                    sections.append(f"- {rule}")
                sections.append("")

        # Architecture
        arch = self._read_md("architecture.md")
        if arch:
            sections.append(arch)
            sections.append("")

        # Naming
        naming = self._read_md("naming.md")
        if naming:
            sections.append(naming)
            sections.append("")

        # Directory Map (condensed)
        dirmap = self._read_md("directory-map.md")
        if dirmap:
            sections.append(dirmap)
            sections.append("")

        # Stack summary
        stack = self._read_json("stack.json")
        if stack:
            sections.append("## Technology Stack")
            summary = stack.get("stack_summary", {})
            for category, packages in summary.items():
                sections.append(f"- **{category}:** {', '.join(packages)}")
            sections.append("")

        # Plans summary
        plans = self._read_md("plans-summary.md")
        if plans:
            sections.append(plans)
            sections.append("")

        # Agent guidelines (from AGENTS.md if exists)
        if index and index.get("agents_md"):
            agents_path = self.context_dir.parent / index["agents_md"]
            if agents_path.exists():
                try:
                    content = agents_path.read_text(encoding="utf-8")
                    sections.append("## Agent Guidelines (from project)")
                    sections.append(content)
                    sections.append("")
                except OSError:
                    pass

        # Footer
        sections.append("---")
        sections.append(
            "This context was generated by Loom-Context. "
            "All suggestions MUST comply with the rules above. "
            "If a request conflicts with these rules, flag it before writing code."
        )

        return "\n".join(sections)

    def _read_md(self, filename: str) -> Optional[str]:
        path = self.context_dir / filename
        if path.exists():
            try:
                return path.read_text(encoding="utf-8")
            except OSError:
                return None
        return None

    def _read_json(self, filename: str) -> Optional[dict[str, Any]]:
        path = self.context_dir / filename
        if path.exists():
            try:
                with open(path, encoding="utf-8") as f:
                    data = json.load(f)
                    return data if isinstance(data, dict) else None
            except (json.JSONDecodeError, OSError):
                return None
        return None
