"""Bundle builder: assembles task-specific context from selected candidates."""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from loom_context import __version__
from loom_context.git import GitHelper
from loom_context.selector.models import BundleManifest
from loom_context.selector.strategies.heuristic import HeuristicStrategy


class BundleBuilder:
    """Builds a task-specific context bundle from .context/ files."""

    def __init__(self, context_dir: Path, root: Path) -> None:
        self.context_dir = context_dir
        self.root = root
        self._git = GitHelper(root)

    def build(
        self,
        task: str,
        max_chars: int = 12000,
        top_k: int = 0,
        strategy: str = "heuristic",
    ) -> Optional[tuple[str, BundleManifest]]:
        """Build a bundle for the given task. Returns (content, manifest) or None."""
        if strategy != "heuristic":
            return None

        selector = HeuristicStrategy(self.context_dir)
        candidates = selector.select(task, max_chars=max_chars)

        # Apply top-k limit if specified
        if top_k > 0 and len(candidates) > top_k:
            candidates = candidates[:top_k]

        if not candidates:
            return None

        # Read project metadata
        index = self._read_index()
        project = index.get("project", {})

        # Assemble bundle content
        lines: list[str] = []
        lines.append(f"# Bundle: {task}")
        lines.append(
            f"**Project:** {project.get('name', '?')} "
            f"({project.get('type', '?')}, "
            f"{', '.join(project.get('architecture', []))})"
        )
        lines.append("")

        included_rules: list[str] = []
        included_docs: list[str] = []
        included_sections: list[str] = []

        for candidate in candidates:
            lines.append(candidate.content)
            lines.append("")

            # Track what was included for manifest
            if candidate.source == "rules":
                included_rules.extend(
                    line.lstrip("- ")
                    for line in candidate.content.split("\n")
                    if line.startswith("- ")
                )
            elif candidate.source in {"plan", "architecture"}:
                included_docs.append(candidate.source)
            included_sections.append(candidate.source)

        # Footer with selection reasons
        lines.append("---")
        lines.append(
            f"*Bundle generated by Loom v{__version__} | "
            f"strategy: {strategy} | "
            f"{len(candidates)} sections selected*"
        )

        content = "\n".join(lines)
        slug = self._slugify(task)

        manifest = BundleManifest(
            task=task,
            slug=slug,
            git_sha=self._git.sha(),
            generated_at=datetime.now(timezone.utc).isoformat(),
            loom_version=__version__,
            selection_strategy=strategy,
            total_candidates=len(candidates),
            included_count=len(candidates),
            total_chars=len(content),
            included_rules=included_rules,
            included_docs=included_docs,
            included_sections=list(set(included_sections)),
        )

        return content, manifest

    def save(
        self,
        task: str,
        max_chars: int = 12000,
        top_k: int = 0,
    ) -> Optional[tuple[Path, Path]]:
        """Build and save bundle to .context/bundles/<slug>/."""
        result = self.build(task, max_chars=max_chars, top_k=top_k)
        if result is None:
            return None

        content, manifest = result
        slug = manifest.slug

        # Create bundle directory
        bundle_dir = self.context_dir / "bundles" / slug
        bundle_dir.mkdir(parents=True, exist_ok=True)

        # Write bundle
        bundle_path = bundle_dir / "bundle.md"
        bundle_path.write_text(content, encoding="utf-8")

        # Write manifest
        manifest_path = bundle_dir / "manifest.json"
        with open(manifest_path, "w", encoding="utf-8") as f:
            json.dump(manifest.to_dict(), f, indent=2, ensure_ascii=False)

        return bundle_path, manifest_path

    def _read_index(self) -> dict:
        """Read .context/index.json."""
        path = self.context_dir / "index.json"
        if not path.exists():
            return {}
        try:
            with open(path, encoding="utf-8") as f:
                return json.load(f)
        except (json.JSONDecodeError, OSError):
            return {}

    def _slugify(self, text: str) -> str:
        """Convert text to a URL-safe slug."""
        text = text.lower().strip()
        text = re.sub(r"[^\w\s-]", "", text)
        text = re.sub(r"[\s_]+", "-", text)
        text = re.sub(r"-+", "-", text)
        return text[:60].strip("-")
