"""Handoff builder: generates session continuity summaries."""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

from loom_context import __version__
from loom_context.git import GitHelper


class HandoffBuilder:
    """Builds a handoff summary for resuming work on a task."""

    def __init__(self, context_dir: Path, loom_dir: Path, root: Path) -> None:
        self.context_dir = context_dir
        self.loom_dir = loom_dir
        self.root = root
        self._git = GitHelper(root)

    def build(self, task: str) -> Optional[str]:
        """Build a handoff summary for the given task."""
        index = self._read_json(self.context_dir / "index.json")
        if not index:
            return None

        project = index.get("project", {})
        lines: list[str] = []

        # Header
        lines.append(f"# Handoff: {task}")
        lines.append(
            f"**Project:** {project.get('name', '?')} "
            f"({project.get('type', '?')}, "
            f"{', '.join(project.get('architecture', []))})"
        )
        sha = self._git.sha()
        branch = self._git.branch()
        lines.append(f"**Branch:** {branch or '?'} | **SHA:** {sha or '?'}")
        lines.append(f"**Generated:** {datetime.now(timezone.utc).isoformat()[:19]}Z")
        lines.append("")

        # Current state: audit findings
        findings = self._read_json(self.loom_dir / "inconsistencies.json")
        if findings:
            errors = findings.get("errors", 0)
            warnings = findings.get("warnings", 0)
            lines.append("## Current State")
            if errors or warnings:
                lines.append(f"- Audit: **{errors} errors**, {warnings} warnings")
                violations = findings.get("violations", [])
                # Group by rule
                by_rule: dict[str, int] = {}
                for v in violations:
                    rule = v.get("rule", "unknown")
                    by_rule[rule] = by_rule.get(rule, 0) + 1
                for rule, count in sorted(by_rule.items(), key=lambda x: -x[1]):
                    lines.append(f"  - {rule}: {count} violations")
            else:
                lines.append("- Audit: clean")
            lines.append("")

        # Recent decisions
        decisions = self._read_jsonl(self.loom_dir / "decisions.jsonl")
        if decisions:
            lines.append("## Recent Decisions")
            for d in decisions[:5]:
                lines.append(f"- **{d.get('summary', '?')}**")
                if d.get("rationale"):
                    lines.append(f"  Why: {d['rationale']}")
            lines.append("")

        # Recent session log
        sessions = self._read_jsonl(self.loom_dir / "sessions.jsonl")
        if sessions:
            lines.append("## Recent Sessions")
            for s in sessions[:5]:
                ts = s.get("timestamp", "")[:19].replace("T", " ")
                lines.append(f"- [{ts}] {s.get('message', '?')}")
            lines.append("")

        # Recent mutations
        mutations = self._read_jsonl(self.loom_dir / "mutations.jsonl")
        if mutations:
            lines.append("## Recent Context Changes")
            for m in mutations[:5]:
                ts = m.get("timestamp", "")[:19].replace("T", " ")
                lines.append(f"- [{ts}] {m.get('action', '?')}: {m.get('summary', '')}")
            lines.append("")

        # Quick rules relevant to task
        quick_rules = index.get("quick_rules", [])
        if quick_rules:
            lines.append("## Active Rules")
            for rule in quick_rules:
                lines.append(f"- {rule}")
            lines.append("")

        # Footer
        lines.append("---")
        lines.append(
            f"*Handoff generated by Loom v{__version__} | "
            f'Use `loom bundle "{task}"` for detailed context*'
        )

        return "\n".join(lines)

    def save(self, task: str) -> Optional[Path]:
        """Build and save handoff to .context/handoffs/."""
        content = self.build(task)
        if content is None:
            return None

        slug = self._slugify(task)
        handoffs_dir = self.context_dir / "handoffs"
        handoffs_dir.mkdir(exist_ok=True)

        path = handoffs_dir / f"{slug}.md"
        path.write_text(content, encoding="utf-8")
        return path

    def _read_json(self, path: Path) -> dict[str, Any]:
        """Read a JSON file."""
        if not path.exists():
            return {}
        try:
            with open(path, encoding="utf-8") as f:
                data: dict[str, Any] = json.load(f)
                return data
        except (json.JSONDecodeError, OSError):
            return {}

    def _read_jsonl(self, path: Path) -> list[dict[str, Any]]:
        """Read a JSONL file, return newest first."""
        if not path.exists():
            return []
        entries: list[dict[str, Any]] = []
        try:
            for line in path.read_text(encoding="utf-8").splitlines():
                line = line.strip()
                if line:
                    entries.append(json.loads(line))
        except (json.JSONDecodeError, OSError):
            pass
        entries.reverse()
        return entries

    def _slugify(self, text: str) -> str:
        """Convert text to a URL-safe slug."""
        text = text.lower().strip()
        text = re.sub(r"[^\w\s-]", "", text)
        text = re.sub(r"[\s_]+", "-", text)
        text = re.sub(r"-+", "-", text)
        return text[:60].strip("-")
